INSERT INTO wcategory (cat_code,cat_name) VALUES ('A00','Housing Expenses');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('A01','Mortgage');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('A02','Rent');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('A03','Electricity');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('A04','Internet/Phone');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('A99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B00','Transportation');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B01','Fuel');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B02','Insurance');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B03','Registration');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B04','Car Service');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B05','Fare');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B06','Parking Fee');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B07','Fines');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('B99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('C00','Medical/Health');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('C01','Insurance');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('C02','Medical Service');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('C03','Medicine/Drugs');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('C04','Health Club');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('C99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D00','Daily Living');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D01','Groceries');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D02','Alcohol');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D03','Clothing');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D04','shoes');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D05','Education/Lessons');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D06','School Supplies/Fees');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D07','Dining/Eating Out');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D08','Office Supplies');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D09','Gifts');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D10','Bank Fee');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D11','License Fee');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D12','Annual Fee');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('D99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('E00','Entertainment');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('E01','Travel/Vacation');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('E02','Movies');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('E99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('F00','Debt');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('F01','Credit Card');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('F99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('G00','Saving');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('G01','Transfer to Savings');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('G99','Other');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('H00','Miscellaneous');
INSERT INTO wcategory (cat_code,cat_name) VALUES ('H99','Other');
